# NATS Configuration
# For a list of complete config options refer to:
# https://beta-docs.nats.io/ref/config


# -------------------------------------------------------------------
#                        INCLUDE CONFIGS
# -------------------------------------------------------------------
# Include configs.
include ./init.conf


# -------------------------------------------------------------------
#                          CONNECTIVITY
# -------------------------------------------------------------------
# Host for client connections.
host: 0.0.0.0

# Port for client connections.
port: 4222


# -------------------------------------------------------------------
#                            JETSTREAM
# -------------------------------------------------------------------
jetstream {
    # Directory to use for file-based storage.
    store_dir: "/data"
    # Maximum size of the file storage. Defaults to up to 1TB if available.
    max_file: 100G
    # Maximum size of the memory storage. Defaults to 75% of available memory.
    max_mem: 1G
}


# -------------------------------------------------------------------
#                         CONFIGURATION
# -------------------------------------------------------------------
# Listen specification <host>:<port> for server monitoring.
http: 0.0.0.0:8222

# Maximum number of active client connections.
max_connections: 64K

# Maximum number of bytes in a message payload. Reducing this size may force you to implement chunking
# in your clients. It is not recommended to use values over 8MB but max_payload can be set up to 64MB.
# The max payload must be equal or smaller to the max_pending value.
max_payload: 1MB

# Duration at which pings are sent to clients, leaf nodes and routes. In the presence of client traffic
# such as messages or client side pings, the server will not send pings.
ping_interval: "2m"

# After how many unanswered pings the server will allow before closing the connection.
ping_max: 2

debug: true
