networks:
    infra:
        driver: bridge
        external: true
        name: infra
        ipam:
            config:
                - subnet: 172.18.0.0/16

services:
    langfuse-worker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: langfuse-worker
        env_file:
            - ./.env
        hostname: langfuse-worker
        image: infra/langfuse-worker:1.0
        networks:
            infra:
                ipv4_address: 172.18.0.7
        restart: unless-stopped
        tty: true
