networks:
    infra:
        driver: bridge
        external: true
        name: infra
        ipam:
            config:
                - subnet: 172.18.0.0/16

services:
    langfuse:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: langfuse
        env_file:
            - ./.env
        hostname: langfuse
        image: infra/langfuse:1.0
        networks:
            infra:
                ipv4_address: 172.18.0.6
        restart: unless-stopped
        tty: true
