networks:
    infra:
        driver: bridge
        external: true
        name: infra
        ipam:
            config:
                - subnet: 172.18.0.0/16

services:
    seaweedfs:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: seaweedfs
        env_file:
            - ./.env
        healthcheck:
            test: ["CMD", "wget", "-qO-", "http://0.0.0.0:9333/cluster/status"]
            interval: 30s
            timeout: 5s
            retries: 3
        hostname: seaweedfs
        image: infra/seaweedfs:1.0
        restart: unless-stopped
        tty: true
        networks:
            infra:
                ipv4_address: 172.18.0.22
        volumes:
            - seaweedfs:/data

volumes:
    seaweedfs:
        driver: local
        name: seaweedfs
