networks:
    infra:
        driver: bridge
        external: true
        name: infra
        ipam:
            config:
                - subnet: 172.18.0.0/16

services:
    kafka-ui:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: kafka-ui
        env_file:
            - ./.env
        hostname: kafka-ui
        image: infra/kafka-ui:1.0
        networks:
            infra:
                ipv4_address: 172.18.0.14
        restart: unless-stopped
        tty: true
