networks:
    infra:
        driver: bridge
        external: true
        name: infra
        ipam:
            config:
                - subnet: 172.18.0.0/16

services:
    consul:
        build:
            context: .
            dockerfile: Dockerfile
            network: host
        container_name: consul
        hostname: consul
        image: infra/consul:1.0
        networks:
            infra:
                ipv4_address: 172.18.0.39
        restart: unless-stopped
        tty: true
        volumes:
            - consul:/consul/data
            - ./config.hcl:/consul/config/config.hcl:ro

volumes:
    consul:
        driver: local
        name: consul
