networks:
    infra:
        driver: bridge
        external: true
        name: infra
        ipam:
            config:
                - subnet: 172.18.0.0/16

services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nginx
        hostname: nginx
        image: infra/nginx:1.0
        restart: unless-stopped
        tty: true
        networks:
            infra:
                ipv4_address: 172.18.0.20
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./migrations:/etc/nginx/conf.d/
            